import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { HelpCircle } from "lucide-react";

export const FAQ = () => {
  const faqs = [
    {
      question: "How does the AI content generation work?",
      answer: "Our AI uses advanced language models trained on billions of text samples to understand context, tone, and style. Simply provide a topic or brief, and our AI will generate high-quality, original content tailored to your needs."
    },
    {
      question: "Is the generated content original and plagiarism-free?",
      answer: "Yes, all content generated by our AI is original and unique. Our system creates new content based on patterns and knowledge rather than copying existing text. However, we recommend running important content through plagiarism checkers as an extra precaution."
    },
    {
      question: "Can I customize the AI to match my brand voice?",
      answer: "Absolutely! Our Professional and Enterprise plans include brand voice training. You can upload examples of your existing content, and our AI will learn to match your specific tone, style, and messaging preferences."
    },
    {
      question: "What types of content can the AI create?",
      answer: "Our AI can create a wide variety of content including blog posts, social media captions, product descriptions, email campaigns, ad copy, press releases, website content, and much more. We're constantly adding new content types based on user feedback."
    },
    {
      question: "How accurate and high-quality is the generated content?",
      answer: "Our AI produces high-quality content that often requires minimal editing. The accuracy and relevance depend on the quality of your input prompts. We recommend providing detailed briefs and reviewing generated content before publication."
    },
    {
      question: "Can I edit and refine the generated content?",
      answer: "Yes! Our platform includes a built-in editor where you can refine, edit, and perfect the generated content. You can also request alternative versions or ask the AI to adjust specific aspects of the content."
    },
    {
      question: "Do you offer a free trial?",
      answer: "Yes, we offer a 14-day free trial for all our paid plans. You can also use our Starter plan indefinitely with 5,000 words per month at no cost. No credit card required for the free trial."
    },
    {
      question: "Is my data and content secure?",
      answer: "Security is our top priority. All data is encrypted in transit and at rest. We never share your content with third parties, and you retain full ownership of all generated content. We're SOC 2 compliant and follow industry best practices."
    },
    {
      question: "Can I integrate the AI with my existing tools?",
      answer: "Yes, our Enterprise plan includes API access and custom integrations. We also offer direct integrations with popular tools like WordPress, Shopify, Mailchimp, and more. Contact our team to discuss specific integration needs."
    },
    {
      question: "What languages does the AI support?",
      answer: "Our AI supports over 30 languages including English, Spanish, French, German, Italian, Portuguese, Dutch, Russian, Chinese, Japanese, and many more. The quality is consistently high across all supported languages."
    }
  ];

  return (
    <section id="faq" className="py-24">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16">
          <div className="inline-flex items-center space-x-2 bg-muted/50 rounded-full px-4 py-2 mb-4">
            <HelpCircle className="h-4 w-4 text-ai-primary" />
            <span className="text-sm font-medium">FAQ</span>
          </div>
          <h2 className="text-3xl md:text-5xl font-bold mb-4">
            Frequently Asked{" "}
            <span className="bg-gradient-primary bg-clip-text text-transparent">
              Questions
            </span>
          </h2>
          <p className="text-lg text-muted-foreground max-w-3xl mx-auto">
            Everything you need to know about our AI content generation platform.
          </p>
        </div>

        <div className="max-w-4xl mx-auto">
          <Accordion type="single" collapsible className="space-y-4">
            {faqs.map((faq, index) => (
              <AccordionItem
                key={index}
                value={`item-${index}`}
                className="bg-gradient-card border border-border rounded-lg px-6"
              >
                <AccordionTrigger className="text-left hover:no-underline hover:text-ai-primary transition-colors">
                  <span className="font-semibold">{faq.question}</span>
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground leading-relaxed">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </div>
    </section>
  );
};